version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/hms-backend/
    overwrite: true
hooks:
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
