export class InternalOpdOverviewVisit {
 
    id:number;
    opd_details_id:number;
    cons_doctor:number;
    case_type:string;
    appointment_date:Date;
    symptoms_type:number;
    symptoms:string;
    bp:string;
    height:string;
    weight:string;
    pulse:string;
    temperature:string;
    respiration:string;
    known_allergies:string;
    patient_old:string;
    casualty:string;
    refference:string;
    date:string;
    note:string;
    note_remark:string;
    payment_mode:string;
    generated_by:string;
    live_consult:string;
    can_delete:string;
    payment_date:Date;
    time:string;
    qty:number;
    opd_id:number;
    charge_id:number;
    standard_charge:number;
    tax:string;
    apply_charge:string;
    amount:string;
    tpa_charge:number;
    created_at:Date;
    patient_id:number;
    global_shift_id:number;
    shift_id:number;
    message:String;
    patient_charge_id:number;
    transaction_id:number;
    Hospital_id:number;
    received_by_name:string;
     payment_gateway: any;
  payment_id: any;
  payment_reference_number: any;
}