export class SettingsGeneralSetting {
    id:number;
    name:string;
    email:string;
    phone:string;
    address:Text;
    start_month:string;
    session_id:number;
    lang_id:number;
    languages:string;
    dise_code:string;
    date_format:string;
    time_format:string;
    currency:string;
    currency_symbol:string;
    is_rtl:string;
    timezone:string;
    image:string;
    mini_logo:string;
    theme:string;
    credit_limit:string;
    opd_record_month:string;
    is_active:string;
    cron_secret_key:string;
    doctor_restriction:string;
    superadmin_restriction:string;
    patient_panel:string;
    mobile_api_url:string;
    app_primary_color_code:string;
    app_secondary_color_code:string;
    app_logo:string;
    zoom_api_key:string;
    zoom_api_secret:string;
    created_at:Date;
    logo:string;
    hos_sch_settings_id:number;
    hospital_id:number;
    hospital_opening_timing:string
    hospital_closing_timing:string
    admin_address:string
    state:string
    district:string
    pincode:string
    website:string
    overview:string
    tax_percentage:any
    tax_amount:any
    lattitude:any
    longitude:any
    hospital_consulting_charge:any
}
