#!/bin/bash

cd /var/www/phr-backend/
cp /home/ubuntu/env/.env.hms .env

# Extract the branch name from GITHUB_REF
BRANCH_NAME=${GITHUB_REF##*/}

echo "GITHUB_REF: $GITHUB_REF"
echo "Branch Name: $BRANCH_NAME"

if [ "$BRANCH_NAME" == "docker-complete" ]; then
    # If branch is 'cloudev', use Docker Compose
    docker-compose up --build -d
else
    # For all other branches, run npm install and build
    npm ci
    echo 'npm package installation'

    npm run build
    echo 'npm build complete'

    # Handle PM2 process management
    if pm2 describe HMS-BE > /dev/null; then
        echo "Restarting existing PM2 process: HMS-BE"
        pm2 restart HMS-BE
    else
        echo "Starting new PM2 process: HMS-BE"
        pm2 start dist/main.js --name HMS-BE
    fi
fi
